apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedemo-api
spec:
  selector:
    matchLabels:
      app: kubedemo-api
  template:
    metadata:
      labels:
        app: kubedemo-api
    spec:
      containers:
      - name: kubedemo-api
        image: kubebackend:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: kubedemo-api 
spec:
  selector:
    app: kubedemo-api
  ports:
  - port: 80  
    targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedemo-ui
spec:
  selector:
    matchLabels:
      app: kubedemo-ui
  template:
    metadata:
      labels:
        app: kubedemo-ui
    spec:
      containers:
      - name: kubedemo-ui
        image: kubefrontend:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubedemo-ui
spec:
  selector:
    app: kubedemo-ui
  ports:
  - type: LoadBalancer
    port: 4100
    targetPort: 80

